import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),C=path.join(ROOT,'inputs/reference_experiments');
const read=p=>fs.readFile(path.join(C,p),'utf8'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function inert(p){const h=await read(p),m=h.match(/<script\b[^>]*type=["']application\/json["'][^>]*>([\s\S]*?)<\/script>/);if(!m)throw Error('JSON missing '+p);return JSON.parse(m[1]);}
const core=await read('T1_source/reference_core.js'),io=await read('T1_source/text_csv.js'),guard=await read('T1_source/record_schema.js');
const s=new Function(core+io+guard+'\nreturn {panelFromCsv,parseCsv,evaluateReplicate,summarizeGroup,decodeReplicatePart,assertCompleteGroup};')();
const csv=await read('data/county_prices.csv');if(sha(csv)!=='f5536401160dc415b33ee7934081484a208aaefc1fa7fd7c6eff6a8b822a906b')throw Error('CSV SHA');const P=s.panelFromCsv(csv,s.parseCsv);
const catalog=JSON.parse(await read('T1_source/actual_records_catalogue.json')),index=JSON.parse(await read('T1_source/actual_indices_catalogue.json')),expected=(await inert('figure_export/inputs/T1_summary.html')).summary;
const fields=['condition_count','observed_count','reference_count','observed_any_count','reference_any_count','fixed_reference_count','fixed_reference_any_count'];
const groups=[];let countFields=0,coefFields=0,coefBitDifferences=0,coefMax=0,summaryFields=0,summaryMax=0;
async function indices(b,L){const parts=index.filter(x=>x.benchmark===b&&x.L===L).sort((a,b)=>a.rep_start-b.rep_start);let meta,pack=[];for(const p of parts){const q=await inert('T1_indices/'+p.title+'.html');const bytes=Buffer.from(q.base64,'base64');if(sha(bytes)!==q.metadata.raw_sha256)throw Error('index part SHA');meta=meta||q.metadata;pack.push(bytes);}const bytes=Buffer.concat(pack);if(sha(bytes)!==meta.whole_group_sha256)throw Error('whole index SHA');return {...meta,bytes,R:1999};}
function compareSummary(actual,ex){for(const [k,v]of Object.entries(ex)){if(typeof v==='number'){const d=Math.abs(v-actual[k]);if(!Number.isFinite(d)||d>1e-12)throw Error('summary '+k);summaryFields++;summaryMax=Math.max(summaryMax,d);}else if(Array.isArray(v))for(let i=0;i<v.length;i++)if(typeof v[i]==='number'){const d=Math.abs(v[i]-actual[k][i]);if(!Number.isFinite(d)||d>1e-12)throw Error('summary interval '+k);summaryFields++;summaryMax=Math.max(summaryMax,d);}}}
for(const g of catalog.groups){const I=await indices(g.benchmark,g.L),saved=[];for(const p of catalog.files.filter(x=>x.metadata.benchmark===g.benchmark&&x.metadata.L===g.L).sort((a,b)=>a.metadata.rep_start-b.metadata.rep_start)){const q=await inert('T1_records/'+p.title+'.html');saved.push(...s.decodeReplicatePart(q,x=>new Uint8Array(Buffer.from(x,'base64'))));}s.assertCompleteGroup(saved);
 const actual=[];for(let rep=0;rep<1999;rep++)for(const name of ['all12','without_Jianping11','without_Jianping_Qingyuan10'])actual.push(s.evaluateReplicate(P,I,rep,name));
 for(let i=0;i<saved.length;i++){const a=actual[i],b=saved[i];if(a.rep!==b.rep||a.cohort!==b.cohort)throw Error('record identity');for(const k of fields){if(a[k]!==b[k])throw Error('count mismatch '+g.benchmark+'/'+g.L+'/'+a.rep+'/'+k);countFields++;}const aa=a.bStar.flat(),bb=b.bStar.flat();if(aa.length!==bb.length)throw Error('coefficient shape');for(let j=0;j<aa.length;j++){const d=Math.abs(aa[j]-bb[j]);if(d>1e-12||!Number.isFinite(d))throw Error('coefficient');coefFields++;coefMax=Math.max(coefMax,d);if(!Object.is(aa[j],bb[j]))coefBitDifferences++;}}
 for(const name of ['all12','without_Jianping11','without_Jianping_Qingyuan10'])compareSummary(s.summarizeGroup(P,I,actual,name),expected.find(x=>x.benchmark===g.benchmark&&x.L===g.L&&x.cohort===name));
 groups.push({benchmark:g.benchmark,L:g.L,rows:actual.length,status:'PASS'});console.log(JSON.stringify(groups.at(-1)));
}
// Retained groups: reproduce N1/N4/N6 from the same five accepted L6 paths.
const rc=await read('T4b_source/screened_reference_core.js'),t=new Function(rc+io+'\nreturn {panelFromCsv,parseCsv,MAIN12,estimateB,baselineIndices,postStats,residuals,evaluateRetainedReplicate,summarizeRetained};')(),TP=t.panelFromCsv(csv,t.parseCsv),texpected=(await inert('figure_export/inputs/T4b_complete_sets_summary.html')).summary;let retainedFields=0;
for(const b of ['B0','B1','B2','B3','B4']){const I=await indices(b,6),q=await inert('T4b_records/T4b_'+b+'_rep1_1999.html'),raw=Buffer.from(q.counts_u16_le_base64,'base64');if(sha(raw)!==q.counts_sha256)throw Error('retained SHA');for(let co=0;co<3;co++){const set=q.cohort_order[co],cols=set.county_ids.map(id=>t.MAIN12.indexOf(id)),base=t.estimateB(TP,b,t.baselineIndices(b)),obs=t.postStats(TP,b,base,cols),res=t.residuals(TP,b,base,cols),rows=[];for(let rep=0;rep<1999;rep++){const r=t.evaluateRetainedReplicate(TP,I,rep,cols,base,obs,res);for(let j=0;j<7;j++){const v=raw.readUInt16LE(((rep*3+co)*7+j)*2),old=v===65535?null:v;if(r[fields[j]]!==old)throw Error('retained count');retainedFields++;}rows.push(r);}compareSummary(t.summarizeRetained(I,rows,obs,cols.length),texpected.find(x=>x.benchmark===b&&x.set_id===set.set_id));}}
const out={status:'PASS',source_csv_sha256:sha(csv),original_45_groups:groups,original_rows:89955,integer_count_fields:countFields,integer_mismatches:0,coefficient_values:coefFields,coefficient_bit_differences:coefBitDifferences,coefficient_max_abs_difference:coefMax,continuous_tolerance:1e-12,retained_count_fields:retainedFields,retained_mismatches:0,summary_numeric_fields:summaryFields,summary_max_abs_difference:summaryMax,script_sha256:sha(await fs.readFile(fileURLToPath(import.meta.url)))};
const OUT=path.resolve(ROOT,process.env.REPLAY_OUT||'reproduction/reference_check.json');await fs.mkdir(path.dirname(OUT),{recursive:true});await fs.writeFile(OUT,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
